# deployment/kubernetes/pv.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: growthscout-gateway-data-pvc
  namespace: growthscout
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
