# deployment/kubernetes/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: growthscout-secrets
  namespace: growthscout
type: Opaque
stringData:
  # Base64 encoded or string representation of secrets in Helm/Kustomize overlays
  API_KEY: "gs_dev_key_12345"
